"""First migration

Revision ID: bd8d1afd4fda
Revises: 8c1ab3a5982b
Create Date: 2022-12-02 20:37:18.866493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8d1afd4fda'
down_revision = '8c1ab3a5982b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('invested_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('fully_invested',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('create_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('create_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('fully_invested',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('invested_amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
